services:
  owguesser:
    build: .
    container_name: owguesser
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.game.rule=Host(`game.yrieix-cisterne.fr`)"
      - "traefik.http.routers.game.entrypoints=websecure"
      - "traefik.http.routers.game.tls.certresolver=letsencrypt"
      - "traefik.http.services.game.loadbalancer.server.port=80"

    networks:
      - traefik

networks:
  traefik:
    external: true