services:
  owguesser:
    build: .
    container_name: owguesser
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owguesser.rule=Host(`owguesser.yrieix-cisterne.fr`)"
      - "traefik.http.routers.owguesser.entrypoints=websecure"
      - "traefik.http.routers.owguesser.tls.certresolver=letsencrypt"
      - "traefik.http.services.owguesser.loadbalancer.server.port=3000"

    networks:
      - traefik

networks:
  traefik:
    external: true